name: sahils-book-shop

services:
  db:
    container_name: mysql-db
    image: mysql:5.7.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: test
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmy-secret-pw"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8800:8800"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DB: test
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"